[[redirects]]
  from = "/api/*"
  to = "${NEXT_PUBLIC_BACKEND_URL}/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "${NEXT_PUBLIC_BACKEND_URL}/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "${NEXT_PUBLIC_BACKEND_URL}/media/:splat"
  status = 200
  force = true
